<a href="https://colab.research.google.com/github/Aniri7777/hello-world/blob/main/NN_for_Language_Processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [184]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense, Dropout, Flatten, RNN, LSTM, Bidirectional, Embedding

from tensorflow.keras.datasets import imdb

# **Time-Depending Model Example**

In [185]:
# inception - one by one layer

In [186]:
# conv1d is better with TimeSerries(и числови данни, а не текстови)

In [187]:
# x<1> -позиция във текста 1, x(1) - със кръгли скоби означаваме слоевете, x[1] - а със квадратни скоби елементите във слоя

In [188]:
### Spars Vector ###
# As for images we have backbones - model, who learn how to make classification of the images(we train it long time for a lots of images)
# Than we can take this model, take the part of it that makes clasification and use the base for other model
# This base makes future extraction and give us a vector, who represent the base
# Spars(vector or matrix) - means that's this vector or matrix has a lot of zeros in it
# One hot incoding - produces Spars vectors
# Multy hot incoding has couple of singles values(1) and a lot more zeros so gives Spars as well

In [189]:
### Dense Vector ###
# Convolutional neural network, ... neural network, transformers - produse Dense Vectors so in the outputs there are very little zeros

# **Recurrent Neural Networks - RNN**

In [190]:
VOCABULARY_SiZE = 10000
OOV = 0
SEQUENCE_LENGHT = 800
EMBEDDING_LENGTH = 256

In [191]:
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words = VOCABULARY_SiZE, oov_char = OOV)

In [192]:
x_train.shape

(25000,)

In [193]:
len(x_train[0]), len(x_train[10])

(218, 450)

In [194]:
#x_train[0]

In [195]:
x_train_padded = tf.keras.utils.pad_sequences(x_train, maxlen = SEQUENCE_LENGHT, padding = "post")

In [196]:
#imdb.get_word_index("the")
imdb.get_word_index()["the"]

1

In [197]:
imdb.get_word_index()["movie"]

17

In [198]:
indices = imdb.get_word_index()

In [199]:
words = {v: k for k, v in indices.items()}

In [200]:
words[14]

'as'

In [201]:
words[1]

'the'

In [202]:
# lstm - modelite sa posledovatelni za da se izpalni 17 element trqbva da svarshi 16ti

In [203]:
model = Sequential([
    Input((SEQUENCE_LENGHT, 32)),
    LSTM(5, return_sequences = True),
    LSTM(10, return_sequences = True),
    LSTM(5),
    Flatten(),
    Dense(VOCABULARY_SiZE, activation = "sigmoid")
])

In [204]:
model.summary()

Model: "sequential_31"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_57 (LSTM)              (None, 800, 5)            760       
                                                                 
 lstm_58 (LSTM)              (None, 800, 10)           640       
                                                                 
 lstm_59 (LSTM)              (None, 5)                 320       
                                                                 
 flatten_11 (Flatten)        (None, 5)                 0         
                                                                 
 dense_27 (Dense)            (None, 10000)             60000     
                                                                 
Total params: 61720 (241.09 KB)
Trainable params: 61720 (241.09 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [205]:
result = model.predict(tf.random.uniform((8, SEQUENCE_LENGHT, 32)))

1/1 [==============================] - 2s 2s/step


In [206]:
result.shape

(8, 10000)

In [207]:
result[:, -20]

array([0.5008159 , 0.500986  , 0.5008443 , 0.50105685, 0.5008308 ,
       0.5009101 , 0.5009049 , 0.50095785], dtype=float32)

In [208]:
bidirectional_model = Sequential([
    Input((SEQUENCE_LENGHT, 32)),
    Bidirectional(LSTM(5, return_sequences = True))
])

In [209]:
bidirectional_model.summary()

Model: "sequential_32"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 bidirectional_3 (Bidirecti  (None, 800, 10)           1520      
 onal)                                                           
                                                                 
Total params: 1520 (5.94 KB)
Trainable params: 1520 (5.94 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [210]:
pca = Sequential([
    Input(10000),
    Dense(128, activation = "relu"),
    Dense(64, activation = "relu"),
    Dense(32, activation = "relu"),
])

In [211]:
pca.summary()

Model: "sequential_33"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_28 (Dense)            (None, 128)               1280128   
                                                                 
 dense_29 (Dense)            (None, 64)                8256      
                                                                 
 dense_30 (Dense)            (None, 32)                2080      
                                                                 
Total params: 1290464 (4.92 MB)
Trainable params: 1290464 (4.92 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [212]:
pca = Sequential([
    Input(10000),
    Dense(32, use_bias = False),
])

In [213]:
pca.summary()

Model: "sequential_34"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_31 (Dense)            (None, 32)                320000    
                                                                 
Total params: 320000 (1.22 MB)
Trainable params: 320000 (1.22 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


Embedding - take one number and make it oneHot, go true only one layer, who dous not have bias term.

In [214]:
tf.one_hot([15], depth = 10000)

<tf.Tensor: shape=(1, 10000), dtype=float32, numpy=array([[0., 0., 0., ..., 0., 0., 0.]], dtype=float32)>

In [215]:
model = Sequential([
    Embedding(input_dim = VOCABULARY_SiZE, output_dim = EMBEDDING_LENGTH, input_length = SEQUENCE_LENGHT),
    LSTM(5, return_sequences = True),
    LSTM(10, return_sequences = True),
    LSTM(5, return_sequences = True),
    #Flatten(),
    Dense(VOCABULARY_SiZE, activation = "softmax")
])

In [216]:
model.summary()

Model: "sequential_35"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_9 (Embedding)     (None, 800, 256)          2560000   
                                                                 
 lstm_61 (LSTM)              (None, 800, 5)            5240      
                                                                 
 lstm_62 (LSTM)              (None, 800, 10)           640       
                                                                 
 lstm_63 (LSTM)              (None, 800, 5)            320       
                                                                 
 dense_32 (Dense)            (None, 800, 10000)        60000     
                                                                 
Total params: 2626200 (10.02 MB)
Trainable params: 2626200 (10.02 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [217]:
x_train_padded[0:5]

array([[   1,   14,   22, ...,    0,    0,    0],
       [   1,  194, 1153, ...,    0,    0,    0],
       [   1,   14,   47, ...,    0,    0,    0],
       [   1,    4,    0, ...,    0,    0,    0],
       [   1,  249, 1323, ...,    0,    0,    0]], dtype=int32)

In [218]:
predictions = model.predict(x_train_padded[0:5])

1/1 [==============================] - 1s 1s/step


In [219]:
tf.argmax(predictions, axis = 1)

<tf.Tensor: shape=(5, 10000), dtype=int64, numpy=
array([[ 48, 228,  79, ...,  78,  48,  53],
       [ 77, 201,  64, ..., 163, 139,  81],
       [ 71, 148,  33, ..., 199, 146,  74],
       [294, 109,  79, ...,  78, 303, 308],
       [149, 103,  39, ...,  38, 104, 158]])>

In [220]:
model.compile(loss = "sparse_categorical_crossentropy")

In [221]:
#model.fit(x_train_padded[0:5], x_train_padded[1:6])

In [222]:
#x_train_padded

In [223]:
#x_train_padded.shape

In [224]:
#x_train_padded[0:5].shape

In [225]:
#x_train_padded[1:6].shape

Beam Search - things couple steps forward

Atention explain - multiple atention, spars atention ... queries -input vector for row, keys - thats what we got for columns

Backbone - do future extraction.

In [227]:
# Transformers - model/gpt2

# **huggingface/transformers**