<a href="https://colab.research.google.com/github/Aniri7777/hello-world/blob/main/thirth_january_deeplearning_beginning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

Fri Jan  3 13:42:17 2025       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   35C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
import tensorflow as tf

In [4]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [5]:
gpu = tf.config.list_physical_devices("GPU")[0]

In [6]:
tf.config.experimental.set_memory_growth(gpu, True)

In [11]:
a = tf.constant(15)
b = tf.constant(38)

In [12]:
a, b

(<tf.Tensor: shape=(), dtype=int32, numpy=15>,
 <tf.Tensor: shape=(), dtype=int32, numpy=38>)

In [13]:
type(a)

tensorflow.python.framework.ops.EagerTensor

In [14]:
tf.multiply(2, a)

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [15]:
tf.multiply(3, b)

<tf.Tensor: shape=(), dtype=int32, numpy=114>

In [17]:
tf.add(tf.multiply(2, a), tf.multiply(3, b)) #събиране - add

<tf.Tensor: shape=(), dtype=int32, numpy=144>

In [18]:
tf.pow(tf.add(tf.multiply(2, a), tf.multiply(3, b)), 2) # повдигане на някаква степен - pow(..., 2)

<tf.Tensor: shape=(), dtype=int32, numpy=20736>

In [19]:
2 * a

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [21]:
a = tf.constant([2, 15, 21, -244, 0, 4])
b = tf.constant([3, 2, 20, 200, 18, 15])

In [22]:
tf.pow(tf.add(tf.multiply(2, a), tf.multiply(3, b)), 2)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([  169,  1296, 10404, 12544,  2916,  2809], dtype=int32)>

In [23]:
2 * a

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([   4,   30,   42, -488,    0,    8], dtype=int32)>

In [24]:
(2 * a + 3 * b) ** 2 # Това също работи и пак връща тензор и умножение на тензор с цисло

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([  169,  1296, 10404, 12544,  2916,  2809], dtype=int32)>

In [26]:
tf.random.uniform((5, 8), 0, 20) # произволна тензорна матрица 5 на 8, със цисла от 0 до 20

<tf.Tensor: shape=(5, 8), dtype=float32, numpy=
array([[ 6.287515  , 13.584061  ,  4.7946167 , 10.722168  , 18.01674   ,
         6.220665  , 14.505124  , 13.552856  ],
       [14.450173  ,  5.460553  ,  7.9930615 , 13.285742  , 13.820581  ,
         3.3458018 , 15.692175  ,  8.480862  ],
       [12.4250145 , 17.24063   ,  8.541999  ,  7.113731  , 17.259373  ,
         5.099895  ,  9.741201  , 11.577789  ],
       [14.86043   ,  0.29265404, 18.333412  ,  7.2117686 , 19.979427  ,
        10.216408  ,  3.1893063 ,  6.8996644 ],
       [ 8.078656  , 19.766161  ,  8.541288  ,  2.4767327 , 14.07753   ,
        11.207802  ,  9.391497  , 10.158324  ]], dtype=float32)>

In [27]:
a = tf.random.uniform((5, 8), 0, 20)
b = tf.random.uniform((5, 8), 0, 20)

In [28]:
a, b

(<tf.Tensor: shape=(5, 8), dtype=float32, numpy=
 array([[ 2.732489 ,  8.921609 , 12.669206 ,  3.030429 ,  3.806553 ,
         16.206045 ,  5.0822377,  3.8849592],
        [18.57219  , 16.59751  , 12.957835 ,  6.1284995,  9.671604 ,
         12.121813 ,  7.492919 ,  4.949186 ],
        [15.899835 , 11.584694 ,  4.480717 ,  2.3605418,  8.501306 ,
          8.190522 ,  3.3623004, 10.925095 ],
        [13.391705 ,  1.2444997, 19.154743 , 12.7627735,  5.8457303,
         11.561298 , 12.96755  , 10.762817 ],
        [12.606192 , 13.824081 ,  7.48523  ,  4.7919965, 15.955443 ,
         15.369862 ,  5.4174924,  4.517951 ]], dtype=float32)>,
 <tf.Tensor: shape=(5, 8), dtype=float32, numpy=
 array([[ 2.0364022 , 19.778002  , 19.868013  ,  7.188916  ,  9.114165  ,
         18.799824  , 17.323503  , 18.49033   ],
        [17.396183  , 17.455729  ,  8.065508  ,  7.970698  , 15.7501335 ,
          1.0967469 , 17.655167  ,  6.906445  ],
        [ 0.05129576,  1.8893647 ,  5.20854   , 16.428692  , 15

In [29]:
(2 * a + 3 * b) ** 2

<tf.Tensor: shape=(5, 8), dtype=float32, numpy=
array([[ 133.96175, 5956.3237 , 7215.22   ,  763.28467, 1221.894  ,
        7887.4937 , 3860.7566 , 3999.412  ],
       [7980.3726 , 7320.892  , 2511.232  , 1308.2034 , 4434.7095 ,
         758.11383, 4617.385  ,  937.4439 ],
       [1021.0297 ,  831.6004 ,  604.52325, 2916.7734 , 3866.2812 ,
         684.0133 , 2749.3281 , 5936.75   ],
       [5860.0933 , 1049.2057 , 8137.7847 , 2927.0435 , 1757.9368 ,
        2726.5278 , 1930.8888 , 2458.883  ],
       [4051.8428 , 2122.6487 , 2082.56   , 1056.6465 , 7833.0776 ,
        1198.0724 , 3885.5107 , 1899.5391 ]], dtype=float32)>

In [32]:
# Гарантираме си, че функцията ще създаде граф или тензор:
@tf.function
def compute(a, b):
  return (2 * a + 3 * b) ** 2

In [33]:
compute(2, 3)

<tf.Tensor: shape=(), dtype=int32, numpy=169>

In [34]:
compute(tf.constant([2]), tf.constant([3]))

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([169], dtype=int32)>

In [35]:
compute(tf.constant([2]), tf.constant([3])).numpy()

array([169], dtype=int32)

In [36]:
compute(a, b) / 100000

<tf.Tensor: shape=(5, 8), dtype=float32, numpy=
array([[0.00133962, 0.05956324, 0.0721522 , 0.00763285, 0.01221894,
        0.07887494, 0.03860757, 0.03999412],
       [0.07980373, 0.07320891, 0.02511232, 0.01308203, 0.0443471 ,
        0.00758114, 0.04617385, 0.00937444],
       [0.0102103 , 0.008316  , 0.00604523, 0.02916773, 0.03866281,
        0.00684013, 0.02749328, 0.0593675 ],
       [0.05860093, 0.01049206, 0.08137785, 0.02927043, 0.01757937,
        0.02726528, 0.01930889, 0.02458883],
       [0.04051843, 0.02122649, 0.0208256 , 0.01056646, 0.07833078,
        0.01198072, 0.03885511, 0.01899539]], dtype=float32)>