<a href="https://colab.research.google.com/github/Aniri7777/hello-world/blob/main/thirth_january_deeplearning_beginning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [65]:
!nvidia-smi

Fri Jan  3 16:22:12 2025       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   69C    P0              30W /  70W |    107MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [66]:
import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense

from sklearn.datasets import load_iris

In [67]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [68]:
gpu = tf.config.list_physical_devices("GPU")[0]

In [69]:
tf.config.experimental.set_memory_growth(gpu, True)

In [70]:
a = tf.constant(15)
b = tf.constant(38)

In [71]:
a, b

(<tf.Tensor: shape=(), dtype=int32, numpy=15>,
 <tf.Tensor: shape=(), dtype=int32, numpy=38>)

In [72]:
type(a)

tensorflow.python.framework.ops.EagerTensor

In [73]:
tf.multiply(2, a)

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [74]:
tf.multiply(3, b)

<tf.Tensor: shape=(), dtype=int32, numpy=114>

In [75]:
tf.add(tf.multiply(2, a), tf.multiply(3, b)) #събиране - add

<tf.Tensor: shape=(), dtype=int32, numpy=144>

In [76]:
tf.pow(tf.add(tf.multiply(2, a), tf.multiply(3, b)), 2) # повдигане на някаква степен - pow(..., 2)

<tf.Tensor: shape=(), dtype=int32, numpy=20736>

In [77]:
2 * a

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [78]:
a = tf.constant([2, 15, 21, -244, 0, 4])
b = tf.constant([3, 2, 20, 200, 18, 15])

In [79]:
tf.pow(tf.add(tf.multiply(2, a), tf.multiply(3, b)), 2)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([  169,  1296, 10404, 12544,  2916,  2809], dtype=int32)>

In [80]:
2 * a

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([   4,   30,   42, -488,    0,    8], dtype=int32)>

In [81]:
(2 * a + 3 * b) ** 2 # Това също работи и пак връща тензор и умножение на тензор с цисло

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([  169,  1296, 10404, 12544,  2916,  2809], dtype=int32)>

In [82]:
tf.random.uniform((5, 8), 0, 20) # произволна тензорна матрица 5 на 8, със цисла от 0 до 20

<tf.Tensor: shape=(5, 8), dtype=float32, numpy=
array([[5.19243002e+00, 1.11420155e+00, 1.00802565e+01, 7.10505962e+00,
        3.47342491e-01, 1.61206455e+01, 1.50418682e+01, 1.06143904e+01],
       [1.31629610e+01, 1.62726517e+01, 8.52584839e-03, 3.12765360e+00,
        1.42451115e+01, 8.53535175e+00, 1.80515747e+01, 1.37611580e+01],
       [1.54136276e+01, 2.57884502e+00, 1.60370522e+01, 1.98879967e+01,
        2.13541985e-01, 1.76238632e+01, 8.05541515e+00, 1.88582954e+01],
       [4.98947859e+00, 9.59739876e+00, 1.55537815e+01, 1.91849136e+01,
        2.29211330e+00, 4.95242119e+00, 8.34485531e+00, 4.09413338e+00],
       [1.99879169e+00, 1.84361496e+01, 1.90778427e+01, 1.91695042e+01,
        8.75675678e-01, 2.89466381e-01, 1.08518295e+01, 1.53369761e+01]],
      dtype=float32)>

In [83]:
a = tf.random.uniform((5, 8), 0, 20)
b = tf.random.uniform((5, 8), 0, 20)

In [84]:
a, b

(<tf.Tensor: shape=(5, 8), dtype=float32, numpy=
 array([[ 1.0918307 , 17.62862   , 13.206973  , 16.514585  , 17.729837  ,
         19.314903  , 16.719702  ,  0.14655352],
        [ 0.30433178,  6.6473603 ,  3.1438708 ,  6.2133    , 16.743689  ,
          6.029055  , 19.651423  ,  6.828656  ],
        [11.395084  ,  9.395035  , 12.170057  ,  3.25176   ,  2.6108503 ,
          5.1605296 , 17.559206  ,  7.839544  ],
        [ 4.859171  , 11.392296  ,  3.106482  , 19.616411  ,  8.352113  ,
          5.6470633 ,  3.0158043 , 10.629604  ],
        [ 2.9059672 ,  8.482804  , 15.267584  ,  4.509535  ,  3.2985663 ,
         14.770348  , 16.175547  , 14.365452  ]], dtype=float32)>,
 <tf.Tensor: shape=(5, 8), dtype=float32, numpy=
 array([[ 8.9537    , 16.921957  , 13.147974  ,  5.8777285 , 19.0639    ,
         18.761452  ,  6.835513  , 15.268607  ],
        [12.734449  , 12.811043  , 13.70241   ,  2.444353  , 19.919876  ,
          1.5404463 ,  4.2695975 ,  1.3879085 ],
        [ 5.0313234 ,  

In [85]:
(2 * a + 3 * b) ** 2

<tf.Tensor: shape=(5, 8), dtype=float32, numpy=
array([[ 843.5982 , 7399.975  , 4337.2593 , 2566.6746 , 8584.277  ,
        9008.698  , 2910.1648 , 2125.111  ],
       [1506.3722 , 2675.7703 , 2246.2837 ,  390.44412, 8695.005  ,
         278.204  , 2715.6228 ,  317.5894 ],
       [1435.208  , 1323.1117 , 5307.221  , 2356.8083 ,  584.9196 ,
        2386.4617 , 8444.489  , 3200.1636 ],
       [ 103.28211, 2169.6921 ,   68.66474, 3802.959  ,  726.1899 ,
        1876.9092 , 1732.8547 , 1186.4441 ],
       [3625.0396 , 1495.8662 , 2073.005  , 1677.5225 , 1479.6704 ,
        6249.7197 , 3115.7017 , 5992.675  ]], dtype=float32)>

In [86]:
# Гарантираме си, че функцията ще създаде граф или тензор:
@tf.function
def compute(a, b):
  return (2 * a + 3 * b) ** 2

In [87]:
compute(2, 3)

<tf.Tensor: shape=(), dtype=int32, numpy=169>

In [88]:
compute(tf.constant([2]), tf.constant([3]))

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([169], dtype=int32)>

In [89]:
compute(tf.constant([2]), tf.constant([3])).numpy()

array([169], dtype=int32)

In [90]:
compute(a, b) / 100000

<tf.Tensor: shape=(5, 8), dtype=float32, numpy=
array([[0.00843598, 0.07399976, 0.04337259, 0.02566675, 0.08584277,
        0.09008698, 0.02910165, 0.02125111],
       [0.01506372, 0.0267577 , 0.02246283, 0.00390444, 0.08695005,
        0.00278204, 0.02715623, 0.00317589],
       [0.01435208, 0.01323112, 0.05307221, 0.02356808, 0.0058492 ,
        0.02386462, 0.0844449 , 0.03200164],
       [0.00103282, 0.02169692, 0.00068665, 0.03802959, 0.0072619 ,
        0.01876909, 0.01732855, 0.01186444],
       [0.03625039, 0.01495866, 0.02073005, 0.01677522, 0.0147967 ,
        0.0624972 , 0.03115702, 0.05992675]], dtype=float32)>

In [91]:
x = tf.constant(5.0)

In [92]:
with tf.GradientTape() as tape:
  tape.watch(x)
  y = x ** 2
  grad_y = tape.gradient(y, x)

In [93]:
grad_y # Получаваме първата производна на х на втора, т.е 2 пъти х = 10 в случая

<tf.Tensor: shape=(), dtype=float32, numpy=10.0>

In [94]:
with tf.GradientTape() as tape:
  tape.watch(x)
  y = tf.sin(x ** 2)
  grad_y = tape.gradient(y, x)

In [95]:
grad_y

<tf.Tensor: shape=(), dtype=float32, numpy=9.912028>

In [96]:
# Gradient decent looks like
#with tf.GradientTape() as tape:
#  grad_y = tape.gradient(loss, model.trainable_params)

In [97]:
iris_attributes, iris_labels = load_iris().data, load_iris().target

In [98]:
iris_attributes.shape[1]

4

In [99]:
num_attributes = iris_attributes.shape[1]
num_classes = len(set(iris_labels))

In [101]:
logistic_regression = Sequential([
    Input(shape = (num_attributes,)),
    Dense(num_classes, activation = "softmax")
])

In [102]:
logistic_regression.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 3)                   │              15 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 15 (60.00 B)

 Trainable params: 15 (60.00 B)

 Non-trainable params: 0 (0.00 B)

In [106]:
logistic_regression.compile(
    optimizer = "sgd",
    loss = "sparse_categorical_crossentropy"
)

In [107]:
logistic_regression.fit(iris_attributes, iris_labels, epochs=100)

Epoch 1/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 85ms/step - loss: 6.1334
Epoch 2/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3.9182  
Epoch 3/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.5709 
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.9640 
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.5979 
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.4344 
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.3565 
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.2816 
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.2368 
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.1840 
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.1517 
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.1177 
Epoch 13/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.0847 
Epoch 14/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.0511 
Epoch 15/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.0160 
Epoch 16/100
5/5 ━

In [110]:
iris_attributes_for_regression = iris_attributes[:, :-1]
iris_targets_for_regression = iris_attributes[:, -1]

In [112]:
linear_regression = Sequential([
    Input(shape=(iris_attributes_for_regression.shape[1],)),  # Use the shape of the data
    Dense(1)
])

In [113]:
linear_regression.compile(
    optimizer = "sgd",
    loss = "mse"
)

In [114]:
linear_regression.fit(iris_attributes_for_regression, iris_targets_for_regression, epochs=100)

Epoch 1/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - loss: 1.1753
Epoch 2/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0928 
Epoch 3/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0794 
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0671 
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0642 
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0542 
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0555 
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0475 
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0547 
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0508 
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0439 
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0432 
Epoch 13/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0440 
Epoch 14/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0396 
Epoch 15/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0516 
Epoch 16/100
5/5 ━━

In [115]:
linear_regression.predict(iris_attributes_for_regression)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step


array([[0.27033114],
       [0.25550887],
       [0.25339025],
       [0.35655037],
       [0.29362485],
       [0.40797776],
       [0.33416283],
       [0.32478523],
       [0.31934053],
       [0.31298766],
       [0.29302007],
       [0.402533  ],
       [0.27002975],
       [0.19651617],
       [0.11513691],
       [0.3108671 ],
       [0.21315365],
       [0.27033114],
       [0.35564226],
       [0.34535557],
       [0.3641137 ],
       [0.33658278],
       [0.15688439],
       [0.39890358],
       [0.548651  ],
       [0.33839998],
       [0.37349123],
       [0.30451626],
       [0.24703746],
       [0.3995083 ],
       [0.37621453],
       [0.26670164],
       [0.35715312],
       [0.27365723],
       [0.31298766],
       [0.16112159],
       [0.16354148],
       [0.30814573],
       [0.2794073 ],
       [0.31026435],
       [0.23614596],
       [0.20347668],
       [0.2969529 ],
       [0.38226402],
       [0.5401796 ],
       [0.27002975],
       [0.39406157],
       [0.316

Deep Feed-Forward Neutral Network